### ISSUE TITLE
恳求大佬能不能做一版R2S plus的适配固件

### ISSUE THREAD

**Issue by Marcoreus89** [DHDAXCW/OpenWrt_RockChip#11]
现在R2S plus有32gb emmc了，但是用大佬发的R2S固件刷入emmc后好像启动不了系统，现在只能用官方固件，很尴尬

**Comment by DusKing1** [comment]
普通版R2S好像也开不了机

**Comment by Marcoreus89** [comment]
> 普通版R2S好像也开不了机

那我不知道，手头没有普通r2s，我是用官方固件写入tf卡再用emmc助手写入的，结果试了大佬的固件还有istoreos都不行，只有写入官方固件到emmc才能开机
