### ISSUE TITLE
刷了6月7日的固件，Doornet 1无线不能使用

### ISSUE THREAD

**Issue by amwsuhje** [DHDAXCW/OpenWrt_RockChip#40]
<img width="1724" alt="1" src="https://github.com/user-attachments/assets/c4887bb6-6585-4f71-ae02-e71aca2c7395">
<img width="1648" alt="2" src="https://github.com/user-attachments/assets/a21f5dfe-29da-4706-a2ae-3102344ef6f8">
工作频率的模式，频段，频宽，信道全部没下拉选项

**Comment by DHDAXCW** [comment]
等下一个版本

**Comment by DHDAXCW** [comment]
刷最新即可
