### ISSUE TITLE
求大神更新一下Rockchip的固件，谢谢大神！

### ISSUE THREAD

**Issue by minminsa666** [DHDAXCW/OpenWrt_RockChip#41]
求大神更新一下Rockchip的固件，从6.7号以来，几乎每天都登上来看看有没有更新。。。现在istore也登不上了，求大神更新，跪谢！

**Comment by selenh** [comment]
是啊，istore获取不到数据了，迫切希望大神更新一下Rockchip的固件。比心~~~

**Comment by Lmn001** [comment]
istore获取不到数据应该是服务器的问题，暂时解决办法要自己手动修复，b站上有说明，可以去看看。

**Comment by DHDAXCW** [comment]
早更了
