### ISSUE TITLE
努比亚Z50 wifi连接不上 

### ISSUE THREAD

**Issue by xhybb** [DHDAXCW/OpenWrt_RockChip#5]
很奇怪 努比亚Z50 wifi连接不上 ，小米、一加、华为都可以连接，网卡MT7921。

Thu Apr  4 23:01:59 2024 daemon.notice netifd: Network device 'phy0-ap0' link is up
Thu Apr  4 23:01:59 2024 kern.info kernel: [  417.839648] IPv6: ADDRCONF(NETDEV_CHANGE): phy0-ap0: link becomes ready
Thu Apr  4 23:01:59 2024 kern.info kernel: [  417.840448] br-lan: port 4(phy0-ap0) entered blocking state
Thu Apr  4 23:01:59 2024 kern.info kernel: [  417.840971] br-lan: port 4(phy0-ap0) entered forwarding state
Thu Apr  4 23:01:59 2024 daemon.notice hostapd: phy0-ap0: interface state HT_SCAN->ENABLED
Thu Apr  4 23:01:59 2024 daemon.notice hostapd: phy0-ap0: AP-ENABLED
Thu Apr  4 23:02:01 2024 daemon.info avahi-daemon[8109]: Joining mDNS multicast group on interface phy0-ap0.IPv6 with address fe80::92e8:68ff:fe13:ceb.
Thu Apr  4 23:02:01 2024 daemon.info avahi-daemon[8109]: New relevant interface phy0-ap0.IPv6 for mDNS.
Thu Apr  4 23:02:01 2024 daemon.info avahi-daemon[8109]: Registering new address record for fe80::92e8:68ff:fe13:ceb on phy0-ap0.*.
Thu Apr  4 23:02:16 2024 daemon.notice hostapd: phy0-ap0: STA 62:94:84:c6:5f:6e IEEE 802.11: did not acknowledge authentication response
Thu Apr  4 23:02:18 2024 daemon.notice hostapd: phy0-ap0: STA 62:94:84:c6:5f:6e IEEE 802.11: did not acknowledge authentication response
Thu Apr  4 23:02:31 2024 daemon.notice hostapd: phy0-ap0: STA 62:94:84:c6:5f:6e IEEE 802.11: did not acknowledge authentication response
Thu Apr  4 23:03:07 2024 daemon.notice hostapd: phy0-ap0: STA 62:94:84:c6:5f:6e IEEE 802.11: did not acknowledge authentication response
Thu Apr  4 23:03:41 2024 daemon.notice hostapd: phy0-ap0: STA 62:94:84:c6:5f:6e IEEE 802.11: did not acknowledge authentication response
Thu Apr  4 23:04:38 2024 daemon.notice hostapd: phy0-ap0: STA 62:94:84:c6:5f:6e IEEE 802.11: did not acknowledge authentication response
Thu Apr  4 23:04:42 2024 daemon.notice hostapd: phy0-ap0: STA 62:94:84:c6:5f:6e IEEE 802.11: did not acknowledge authentication response
Thu Apr  4 23:04:47 2024 daemon.notice hostapd: phy0-ap0: STA 62:94:84:c6:5f:6e IEEE 802.11: did not acknowledge authentication response

**Comment by DHDAXCW** [comment]
努比亚那个密码删了再试试？不行的话你把WiFi改WPS2试试吧

**Comment by xhybb** [comment]
不行还是连不上，笔记本网卡Wireless-AC 3165也无法连接，改成2.4G所有设备都连接上。

**Comment by DHDAXCW** [comment]
截图看看网卡怎么设置的

**Comment by xhybb** [comment]
![QQ截图20240405203937](https://gi
![QQ截图20240405204116](https://github.com/DHDAXCW/OpenWrt_RockChip/assets/19210186/d92f8fca-619b-46d5-a984-16e0171c2e76)
![QQ截图20240405204132](https://github.com/DHDAXCW/OpenWrt_RockChip/assets/19210186/5c74bf95-d3ed-48df-9e81-3b84b00d0d6e)
![QQ截图20240405204220](https://github.com/DHDAXCW/OpenWrt_RockChip/assets/19210186/fcb42b09-9ab7-4a95-99c0-88465a0217eb)
thub.com/DHDAXCW/OpenWrt_RockChip/assets/19210186/12f7a06d-4483-4deb-a926-7a4501f0c903)
![QQ截图20240405204054](https://github.com/DHDAXCW/OpenWrt_RockChip/assets/19210186/deea44d3-b03d-422a-ac94-761bafec0981)

**Comment by xhybb** [comment]
![QQ截图20240405203937](https://github.com/DHDAXCW/OpenWrt_RockChip/assets/19210186/c732215c-2894-4876-a035-f4f92193068e)

**Comment by DHDAXCW** [comment]
ax 44 80 5g 试试

**Comment by xhybb** [comment]
算了不折腾了，就努比亚还不行，我外挂AP解决了。
