### ISSUE TITLE
可否添加新Wifi网卡的支持

### ISSUE THREAD

**Issue by Kai0531** [DHDAXCW/OpenWrt_RockChip#6]
目前手上有TP-Link TL-WDN4200 V1.0 的网卡和小米随身WiFi两个网卡设备，请问可否能添加相应网卡驱动呢，谢谢

据网上查询两者分别使用Ralink RT3573及MT7601UN

**Comment by DHDAXCW** [comment]
这有点老，换个好的吧。。。
